"""add solana_network to user_profiles

Revision ID: dd0ea921ac7c
Revises: 754cd0dfe3ab
Create Date: 2026-01-03 01:36:38.676749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0ea921ac7c'
down_revision: Union[str, Sequence[str], None] = '754cd0dfe3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('solana_network', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'solana_network')
    # ### end Alembic commands ###
