"""add waitlist table

Revision ID: 1719e279ea1b
Revises: cfc1dc3075b8
Create Date: 2026-04-19 14:54:20.947781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1719e279ea1b'
down_revision: Union[str, Sequence[str], None] = 'cfc1dc3075b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('referral_code', sa.String(length=8), nullable=False),
    sa.Column('referred_by_code', sa.String(length=8), nullable=True),
    sa.Column('referred_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('messages_today', sa.Integer(), nullable=True),
    sa.Column('messages_reset_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('daily_alpha_enabled', sa.Boolean(), nullable=True),
    sa.Column('wallet_address_shared', sa.String(length=64), nullable=True),
    sa.Column('joined_via', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_referral_code'), 'waitlist', ['referral_code'], unique=True)
    op.create_index(op.f('ix_waitlist_status'), 'waitlist', ['status'], unique=False)
    op.create_index(op.f('ix_waitlist_telegram_user_id'), 'waitlist', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_telegram_user_id'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_status'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_referral_code'), table_name='waitlist')
    op.drop_table('waitlist')
    # ### end Alembic commands ###
