"""Add OAuth fields to user_mcp_servers and mcp_oauth_pending table

Revision ID: 754cd0dfe3ab
Revises: b1b74b54caae
Create Date: 2025-12-30 02:06:51.838222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754cd0dfe3ab'
down_revision: Union[str, Sequence[str], None] = 'b1b74b54caae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_oauth_pending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('mcp_server_name', sa.String(length=64), nullable=False),
    sa.Column('mcp_server_url', sa.String(length=512), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('authorization_endpoint', sa.String(length=512), nullable=False),
    sa.Column('token_endpoint', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_oauth_pending_state'), 'mcp_oauth_pending', ['state'], unique=True)
    op.create_index(op.f('ix_mcp_oauth_pending_user_id'), 'mcp_oauth_pending', ['user_id'], unique=False)
    op.add_column('user_mcp_servers', sa.Column('auth_type', sa.String(length=20), nullable=True))
    op.add_column('user_mcp_servers', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('user_mcp_servers', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('user_mcp_servers', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mcp_servers', 'token_expires_at')
    op.drop_column('user_mcp_servers', 'refresh_token')
    op.drop_column('user_mcp_servers', 'access_token')
    op.drop_column('user_mcp_servers', 'auth_type')
    op.drop_index(op.f('ix_mcp_oauth_pending_user_id'), table_name='mcp_oauth_pending')
    op.drop_index(op.f('ix_mcp_oauth_pending_state'), table_name='mcp_oauth_pending')
    op.drop_table('mcp_oauth_pending')
    # ### end Alembic commands ###
