"""add sign_sessions tables

Revision ID: 787223607842
Revises: ddccb5891444
Create Date: 2026-04-21 21:22:32.113912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787223607842'
down_revision: Union[str, Sequence[str], None] = 'ddccb5891444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('viewer_token_hash', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('from_token', sa.String(length=64), nullable=True),
    sa.Column('to_token', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('to_address', sa.String(length=64), nullable=True),
    sa.Column('slippage_bps', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=20), nullable=True),
    sa.Column('reference_key', sa.String(length=64), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('execution_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('from_symbol', sa.String(length=20), nullable=True),
    sa.Column('to_symbol', sa.String(length=20), nullable=True),
    sa.Column('output_amount', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('price_impact', sa.String(length=64), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('fee_bps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sign_sessions_reference_key'), 'sign_sessions', ['reference_key'], unique=False)
    op.create_index(op.f('ix_sign_sessions_status'), 'sign_sessions', ['status'], unique=False)
    op.create_table('sign_session_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sign_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sign_session_events_session_id'), 'sign_session_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sign_session_events_session_id'), table_name='sign_session_events')
    op.drop_table('sign_session_events')
    op.drop_index(op.f('ix_sign_sessions_status'), table_name='sign_sessions')
    op.drop_index(op.f('ix_sign_sessions_reference_key'), table_name='sign_sessions')
    op.drop_table('sign_sessions')
    # ### end Alembic commands ###
