"""Add user_mcp_servers table

Revision ID: ae576c581e64
Revises: fdb7f10850b8
Create Date: 2025-12-30 01:43:35.980207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae576c581e64'
down_revision: Union[str, Sequence[str], None] = 'fdb7f10850b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_mcp_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_user_mcp_name')
    )
    op.create_index(op.f('ix_user_mcp_servers_is_active'), 'user_mcp_servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_mcp_servers_user_id'), 'user_mcp_servers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mcp_servers_user_id'), table_name='user_mcp_servers')
    op.drop_index(op.f('ix_user_mcp_servers_is_active'), table_name='user_mcp_servers')
    op.drop_table('user_mcp_servers')
    # ### end Alembic commands ###
