"""Add api_key to user_mcp_servers

Revision ID: b1b74b54caae
Revises: ae576c581e64
Create Date: 2025-12-30 01:51:53.636709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b74b54caae'
down_revision: Union[str, Sequence[str], None] = 'ae576c581e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_mcp_servers', sa.Column('api_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mcp_servers', 'api_key')
    # ### end Alembic commands ###
