"""add dual signing mode columns to user_profiles

Revision ID: cfc1dc3075b8
Revises: dd0ea921ac7c
Create Date: 2026-04-16 23:39:42.017348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc1dc3075b8'
down_revision: Union[str, Sequence[str], None] = 'dd0ea921ac7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('signing_mode', sa.String(length=20), nullable=False, server_default='internal'))
    op.add_column('user_profiles', sa.Column('external_wallet_address', sa.String(length=64), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_wallet_app', sa.String(length=20), nullable=False, server_default='phantom'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_wallet_app')
    op.drop_column('user_profiles', 'external_wallet_address')
    op.drop_column('user_profiles', 'signing_mode')
    # ### end Alembic commands ###
