"""add bouncer_score and remarks to waitlist

Revision ID: ddccb5891444
Revises: 1719e279ea1b
Create Date: 2026-04-19 17:54:26.056701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddccb5891444'
down_revision: Union[str, Sequence[str], None] = '1719e279ea1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist', sa.Column('bouncer_score', sa.Integer(), nullable=True))
    op.add_column('waitlist', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist', 'remarks')
    op.drop_column('waitlist', 'bouncer_score')
    # ### end Alembic commands ###
