"""add_user_triggers_table

Revision ID: e78af2d18db9
Revises: 3490c6102f6a
Create Date: 2026-05-19 23:59:25.150450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e78af2d18db9'
down_revision: Union[str, Sequence[str], None] = '3490c6102f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('elfa_query_id', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('elfa_query_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['user_profiles.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_triggers_elfa_query_id'), 'user_triggers', ['elfa_query_id'], unique=True)
    op.create_index(op.f('ix_user_triggers_status'), 'user_triggers', ['status'], unique=False)
    op.create_index(op.f('ix_user_triggers_telegram_user_id'), 'user_triggers', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_triggers_telegram_user_id'), table_name='user_triggers')
    op.drop_index(op.f('ix_user_triggers_status'), table_name='user_triggers')
    op.drop_index(op.f('ix_user_triggers_elfa_query_id'), table_name='user_triggers')
    op.drop_table('user_triggers')
    # ### end Alembic commands ###
