"""Add wallet_alerts and helius_webhook_config

Revision ID: fdb7f10850b8
Revises: 09e3d698ca3d
Create Date: 2025-12-29 16:33:06.541591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdb7f10850b8'
down_revision: Union[str, Sequence[str], None] = '09e3d698ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helius_webhook_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.String(length=128), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('watched_wallet', sa.String(length=64), nullable=False),
    sa.Column('wallet_label', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_alerts_is_active'), 'wallet_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_wallet_alerts_user_id'), 'wallet_alerts', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallet_alerts_watched_wallet'), 'wallet_alerts', ['watched_wallet'], unique=False)
    op.create_table('watched_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_address', sa.String(length=64), nullable=False),
    sa.Column('token_symbol', sa.String(length=32), nullable=True),
    sa.Column('token_name', sa.String(length=128), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('discovered_price', sa.Numeric(precision=24, scale=12), nullable=True),
    sa.Column('discovered_mc', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('momentum_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_tokens_token_address'), 'watched_tokens', ['token_address'], unique=False)
    op.create_index(op.f('ix_watched_tokens_user_id'), 'watched_tokens', ['user_id'], unique=False)
    # NOTE: Skipping drops of legacy Prisma tables (Transaction, User, etc.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_tokens_user_id'), table_name='watched_tokens')
    op.drop_index(op.f('ix_watched_tokens_token_address'), table_name='watched_tokens')
    op.drop_table('watched_tokens')
    op.drop_index(op.f('ix_wallet_alerts_watched_wallet'), table_name='wallet_alerts')
    op.drop_index(op.f('ix_wallet_alerts_user_id'), table_name='wallet_alerts')
    op.drop_index(op.f('ix_wallet_alerts_is_active'), table_name='wallet_alerts')
    op.drop_table('wallet_alerts')
    op.drop_table('helius_webhook_config')
    # ### end Alembic commands ###
